### ISSUE TITLE
We need to also uprade the headers package when upgrading this

### ISSUE THREAD

**Issue by yw662** [alanorth/aur-linux-clear-bin#2]
Or the headers package will be unusable.

Should I upgrade the headers package or will you do that ?

**Comment by alanorth** [comment]
Oops, you're right. I forgot to update the headers because I wasn't using them, but I've just updated them to `5.2.9-825` from Clear 30840 to match the kernel now. :cry:

I will try to find time this week to update the PKGBUILD for the headers to match the newer style of the kernel.
